# Generated by Django 4.0.6 on 2022-07-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('rubric', models.SmallIntegerField(choices=[(1, 'Геодезические'), (2, 'Подготовительные'), (3, 'Земляные'), (4, 'Каменные'), (5, 'Бетонные/железобетонные'), (6, 'Монтажные'), (7, 'Кровельные'), (8, 'Отделочные'), (9, 'Изоляционные'), (10, 'Слаботочные')], default='Подготовительные', verbose_name='Вид работ')),
                ('preamble', models.CharField(max_length=512, verbose_name='Вступление')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Основной текст')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='картинка к новости')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Корректирована')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалена(помечена удаленной)')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ('-created',),
            },
        ),
    ]
