# Generated by Django 4.0.6 on 2022-07-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(max_length=255, null=True, upload_to='images/', verbose_name='картинка к новости'),
        ),
    ]
