# Generated by Django 4.0.6 on 2022-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/project_<django.db.models.fields.related.ForeignKey>', verbose_name='Фото проектов'),
        ),
    ]
