# Generated by Django 4.0.6 on 2022-07-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/projects', verbose_name='Фото проектов'),
        ),
    ]
