# Generated by Django 4.0.6 on 2022-07-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_emailer_alter_newspicture_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emailer',
        ),
    ]
